# -*- coding: utf-8 -*-
"""China.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZLNQQS4MlocqHZacDPkiWYS6pa7LqEK9
"""

# Programa desarrollado por: Samuel Izquierdo Cuervo
# Proyecto escolar: LA GEOPOLÍTICA DE CHINA
# Versión mejorada con colores y diseño visual para Google Colab

from IPython.display import display, HTML, clear_output
from textwrap import fill
import unicodedata
import time

# ============================================================
# ESTILOS VISUALES
# ============================================================

def cargar_estilos():
    display(HTML("""
    <style>
        .hero {
            background: linear-gradient(135deg, #8B0000, #C62828, #E53935);
            color: white;
            padding: 26px;
            border-radius: 20px;
            margin: 10px 0 18px 0;
            box-shadow: 0 8px 20px rgba(0,0,0,0.25);
        }
        .hero h1 {
            margin: 0;
            font-size: 34px;
        }
        .hero p {
            margin-top: 10px;
            font-size: 16px;
        }
        .subhero {
            background: linear-gradient(135deg, #0D47A1, #1976D2);
            color: white;
            padding: 18px;
            border-radius: 16px;
            margin: 10px 0 18px 0;
            box-shadow: 0 6px 14px rgba(0,0,0,0.18);
        }
        .card {
            background: #ffffff;
            border-left: 8px solid #1565C0;
            padding: 16px;
            margin: 12px 0;
            border-radius: 14px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.10);
        }
        .card-red {
            background: #fff5f5;
            border-left: 8px solid #C62828;
            padding: 16px;
            margin: 12px 0;
            border-radius: 14px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.10);
        }
        .card-green {
            background: #f1fff5;
            border-left: 8px solid #2E7D32;
            padding: 16px;
            margin: 12px 0;
            border-radius: 14px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.10);
        }
        .card-gold {
            background: #fff9e6;
            border-left: 8px solid #F9A825;
            padding: 16px;
            margin: 12px 0;
            border-radius: 14px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.10);
        }
        .menu-box {
            display: grid;
            grid-template-columns: repeat(2, minmax(250px, 1fr));
            gap: 12px;
            margin-top: 10px;
        }
        .menu-item {
            background: linear-gradient(135deg, #ffffff, #f4f7fb);
            border: 1px solid #d9e2ef;
            padding: 14px;
            border-radius: 14px;
            box-shadow: 0 3px 8px rgba(0,0,0,0.08);
            font-size: 15px;
        }
        .tag {
            display: inline-block;
            background: #1565C0;
            color: white;
            padding: 5px 10px;
            border-radius: 999px;
            font-size: 12px;
            margin-bottom: 6px;
        }
        .footer-box {
            background: #f3f8ff;
            border-left: 8px solid #1976D2;
            padding: 15px;
            border-radius: 14px;
            margin-top: 18px;
        }
        .score-box {
            background: linear-gradient(135deg, #1B5E20, #43A047);
            color: white;
            padding: 20px;
            border-radius: 16px;
            box-shadow: 0 6px 14px rgba(0,0,0,0.2);
            margin-top: 12px;
        }
    </style>
    """))

# ============================================================
# DATOS BASE DEL PROGRAMA
# ============================================================

CONCEPTOS_AVANZADOS = {
    "Trampa de Tucídides": "Idea de que una potencia emergente puede entrar en conflicto con una potencia dominante cuando cambia el equilibrio de poder.",
    "Multipolaridad": "Mundo donde existen varias potencias importantes y no solo una con dominio absoluto.",
    "Decoupling": "Separación económica y tecnológica entre países o bloques para reducir dependencia mutua.",
    "Sharp power": "Influencia política indirecta mediante medios, cultura, economía, información o tecnología.",
    "Diplomacia de deuda": "Influencia generada cuando un país presta dinero o financia proyectos y eso crea dependencia.",
    "Seguridad económica": "Protección de industrias clave como energía, chips, alimentos, puertos, datos y tecnología."
}

TRIVIA_PREGUNTAS = [
    {
        "pregunta": "¿Qué país es el principal rival estratégico de China?",
        "respuesta_mostrada": "Estados Unidos",
        "validas": ["estados unidos", "usa", "eeuu", "eua", "estadosunidos"],
        "explicacion": "China y Estados Unidos compiten en comercio, tecnología, poder militar e influencia global."
    },
    {
        "pregunta": "¿Por qué Taiwán es importante?",
        "respuesta_mostrada": "Por su producción de semiconductores avanzados",
        "validas": ["semiconductores avanzados", "chips avanzados", "por su produccion de semiconductores avanzados", "por los chips"],
        "explicacion": "Taiwán ocupa una posición crítica en la fabricación de chips avanzados usados en múltiples industrias."
    },
    {
        "pregunta": "¿Qué busca la Ruta de la Seda?",
        "respuesta_mostrada": "Expandir la influencia china mediante infraestructura, comercio y financiamiento",
        "validas": ["expandir la influencia china", "infraestructura comercio y financiamiento", "expandir influencia con infraestructura"],
        "explicacion": "China utiliza infraestructura y financiamiento como herramientas de proyección internacional."
    },
    {
        "pregunta": "¿Qué empresa china es famosa por 5G?",
        "respuesta_mostrada": "Huawei",
        "validas": ["huawei"],
        "explicacion": "Huawei es una empresa clave en telecomunicaciones y redes 5G."
    },
    {
        "pregunta": "¿Qué significa multipolaridad?",
        "respuesta_mostrada": "Un mundo donde existen varias potencias importantes",
        "validas": ["varias potencias importantes", "mundo con varias potencias", "un mundo con varias potencias"],
        "explicacion": "La multipolaridad describe un sistema internacional menos concentrado en una sola superpotencia."
    }
]

ESCENARIOS = {
    "A": {
        "titulo": "China invade Taiwán",
        "consecuencias": [
            "Crisis mundial de semiconductores.",
            "Posible respuesta militar o económica de Estados Unidos.",
            "Caída de bolsas internacionales.",
            "Afectación a celulares, autos, IA y computadoras.",
            "Empresas buscarían proveedores alternativos."
        ],
        "impacto": "Sería uno de los shocks económicos y tecnológicos más graves del siglo. La seguridad económica se volvería prioridad absoluta."
    },
    "B": {
        "titulo": "Estados Unidos bloquea chips avanzados a China",
        "consecuencias": [
            "China acelera su autosuficiencia tecnológica.",
            "Empresas chinas enfrentan retrasos.",
            "Aumenta la tensión comercial.",
            "Otros países ganan importancia en cadenas de suministro."
        ],
        "impacto": "El decoupling tecnológico se profundizaría y las empresas tendrían que rediseñar compras, producción y alianzas."
    },
    "C": {
        "titulo": "México aumenta su comercio con China",
        "consecuencias": [
            "Más importaciones baratas.",
            "Oportunidades para consumidores y empresas.",
            "Riesgo de presión política de Estados Unidos.",
            "Competencia para fabricantes mexicanos.",
            "Posibilidad de atraer inversión china."
        ],
        "impacto": "México ganaría margen comercial, pero también debería equilibrar cuidadosamente su relación con Washington."
    },
    "D": {
        "titulo": "China controla rutas marítimas estratégicas",
        "consecuencias": [
            "Mayor influencia sobre comercio global.",
            "Riesgo para países dependientes de esas rutas.",
            "Aumento en costos de transporte y seguros.",
            "Mayor presión sobre Estados Unidos y sus aliados."
        ],
        "impacto": "El control marítimo elevaría el poder geoeconómico chino y afectaría cadenas logísticas mundiales."
    }
}

# ============================================================
# FUNCIONES DE APOYO
# ============================================================

def normalizar_texto(texto):
    texto = texto.strip().lower()
    texto = "".join(
        c for c in unicodedata.normalize("NFD", texto)
        if unicodedata.category(c) != "Mn"
    )
    return texto

def limpiar_pantalla():
    clear_output(wait=True)
    cargar_estilos()

def imprimir_parrafo(texto, ancho=100):
    print(fill(texto, width=ancho))

def mostrar_hero(titulo, subtitulo):
    display(HTML(f"""
    <div class="hero">
        <h1>🌏 {titulo}</h1>
        <p>{subtitulo}</p>
    </div>
    """))

def mostrar_subhero(titulo, subtitulo):
    display(HTML(f"""
    <div class="subhero">
        <h2 style="margin:0;">{titulo}</h2>
        <p style="margin:8px 0 0 0;">{subtitulo}</p>
    </div>
    """))

def mostrar_tarjeta(titulo, contenido, clase="card"):
    display(HTML(f"""
    <div class="{clase}">
        <h3 style="margin-top:0;">{titulo}</h3>
        <p style="margin-bottom:0; line-height:1.6;">{contenido}</p>
    </div>
    """))

def pausa_regreso():
    print("\n↩️ Regresando al centro de análisis...")
    input("Pulsa Enter para continuar...")
    time.sleep(0.4)

# ============================================================
# BIENVENIDA Y MENÚ
# ============================================================

def mostrar_bienvenida():
    limpiar_pantalla()
    mostrar_hero(
        "LA GEOPOLÍTICA DE CHINA",
        "Mini centro interactivo de análisis geopolítico • Google Colab • Modo analista geopolítico activado"
    )

    mostrar_tarjeta(
        "🚀 Bienvenido/a",
        "Este programa funciona como una mini página web interactiva dentro de Google Colab. "
        "Aquí podrás explorar tensiones globales, relaciones estratégicas, riesgos económicos, "
        "tecnología, trivia y escenarios internacionales relacionados con China.",
        "card-gold"
    )

    display(HTML("""
    <div class="footer-box">
        <b>🧭 Qué puedes hacer aquí:</b><br>
        • Consultar temas estratégicos<br>
        • Responder una trivia geopolítica<br>
        • Usar un simulador internacional<br>
        • Regresar al menú las veces que quieras
    </div>
    """))

    input("\n▶️ Pulsa Enter para entrar al centro de análisis...")

def mostrar_menu():
    limpiar_pantalla()
    mostrar_subhero("📚 MENÚ PRINCIPAL", "Selecciona un tema para generar tu reporte estratégico")

    display(HTML("""
    <div class="menu-box">
        <div class="menu-item"><span class="tag">1</span><br><b>Objetivo geopolítico de China</b></div>
        <div class="menu-item"><span class="tag">2</span><br><b>Relación China - Estados Unidos</b></div>
        <div class="menu-item"><span class="tag">3</span><br><b>Taiwán y el riesgo de conflicto</b></div>
        <div class="menu-item"><span class="tag">4</span><br><b>Ruta de la Seda / Belt and Road Initiative</b></div>
        <div class="menu-item"><span class="tag">5</span><br><b>Tecnología: IA, chips, 5G y Huawei</b></div>
        <div class="menu-item"><span class="tag">6</span><br><b>China en América Latina y México</b></div>
        <div class="menu-item"><span class="tag">7</span><br><b>Mar del Sur de China</b></div>
        <div class="menu-item"><span class="tag">8</span><br><b>China y Rusia</b></div>
        <div class="menu-item"><span class="tag">9</span><br><b>Riesgos económicos internos</b></div>
        <div class="menu-item"><span class="tag">10</span><br><b>Modo trivia</b></div>
        <div class="menu-item"><span class="tag">11</span><br><b>Simulador “¿Qué pasaría si...?”</b></div>
        <div class="menu-item"><span class="tag">12</span><br><b>Salir</b></div>
    </div>
    """))

def pedir_opcion_menu():
    while True:
        opcion = input("\n🔎 Escribe el número de la opción que deseas consultar: ").strip()
        if opcion in [str(i) for i in range(1, 13)]:
            return opcion
        print("⚠️ Opción no válida. Escribe un número del 1 al 12.")

# ============================================================
# MOTOR DE TEMAS
# ============================================================

def mostrar_conceptos(claves):
    if not claves:
        return

    conceptos_html = ""
    for clave in claves:
        definicion = CONCEPTOS_AVANZADOS.get(clave, "")
        conceptos_html += f"<li><b>{clave}:</b> {definicion}</li>"

    display(HTML(f"""
    <div class="card-green">
        <h3 style="margin-top:0;">📘 Conceptos avanzados relacionados</h3>
        <ul style="line-height:1.7; margin-bottom:0;">
            {conceptos_html}
        </ul>
    </div>
    """))

def mostrar_tema(titulo, resumen, importancia, impacto, dato, reflexion, conceptos):
    limpiar_pantalla()
    mostrar_hero(titulo, "Reporte estratégico generado")

    mostrar_tarjeta("📌 Resumen", resumen, "card")
    mostrar_tarjeta("🌐 Importancia", importancia, "card-red")
    mostrar_tarjeta("💼 Impacto en negocios", impacto, "card")
    mostrar_tarjeta("✨ Dato interesante", dato, "card-gold")
    mostrar_conceptos(conceptos)
    mostrar_tarjeta("🧠 Pregunta de reflexión", reflexion, "card-green")

    input("\n✍️ Pulsa Enter para volver al menú principal...")
    pausa_regreso()

# ============================================================
# TEMAS
# ============================================================

def tema_1():
    mostrar_tema(
        "1. OBJETIVO GEOPOLÍTICO DE CHINA",
        "China busca convertirse en una potencia global en lo económico, tecnológico, militar y diplomático. "
        "Su estrategia está ligada al rejuvenecimiento nacional impulsado por Xi Jinping.",
        "Esto cambia el equilibrio mundial porque China ya no acepta un sistema internacional dominado por completo por Estados Unidos.",
        "Las empresas deben considerar a China como mercado, proveedor, competidor y riesgo geopolítico al mismo tiempo.",
        "China combina capitalismo de mercado con fuerte control estatal.",
        "¿Puede una economía crecer más rápido cuando el Estado dirige estratégicamente sus industrias?",
        ["Multipolaridad", "Sharp power", "Seguridad económica"]
    )

def tema_2():
    mostrar_tema(
        "2. RELACIÓN CHINA - ESTADOS UNIDOS",
        "China y Estados Unidos son socios comerciales, pero también rivales estratégicos en comercio, tecnología, IA, chips e influencia global.",
        "Es una de las rivalidades más importantes del siglo XXI.",
        "Las empresas enfrentan aranceles, sanciones, restricciones tecnológicas y cambios en cadenas de suministro.",
        "Aunque compiten, sus economías siguen profundamente conectadas.",
        "¿Es posible que dos países sean enemigos estratégicos y socios económicos al mismo tiempo?",
        ["Trampa de Tucídides", "Decoupling"]
    )

def tema_3():
    mostrar_tema(
        "3. TAIWÁN Y EL RIESGO DE CONFLICTO",
        "China considera a Taiwán parte de su territorio, mientras Taiwán funciona con gobierno propio y apoyo político-militar de Estados Unidos.",
        "Un conflicto en Taiwán afectaría la economía mundial por su papel central en semiconductores avanzados.",
        "Podría provocar escasez de chips para celulares, autos, computadoras, inteligencia artificial y equipos médicos.",
        "Taiwán es pequeño en territorio, pero enorme en importancia tecnológica.",
        "¿Qué pasaría con las empresas si se detiene la producción de chips?",
        ["Seguridad económica", "Decoupling"]
    )

def tema_4():
    mostrar_tema(
        "4. RUTA DE LA SEDA / BELT AND ROAD INITIATIVE",
        "China financia y construye infraestructura en otros países para expandir rutas comerciales y su influencia política y económica.",
        "Le permite ganar acceso a recursos, puertos, carreteras, trenes y aliados estratégicos.",
        "Abre oportunidades de inversión y comercio, pero también puede crear dependencia financiera.",
        "China muchas veces influye más mediante deuda, comercio e infraestructura que mediante fuerza militar.",
        "¿La inversión china es una oportunidad o una forma de dependencia?",
        ["Diplomacia de deuda", "Sharp power"]
    )

def tema_5():
    mostrar_tema(
        "5. TECNOLOGÍA: IA, CHIPS, 5G Y HUAWEI",
        "China busca liderar inteligencia artificial, telecomunicaciones 5G, autos eléctricos, vigilancia digital y semiconductores.",
        "La tecnología define quién tendrá más poder económico y militar en el futuro.",
        "Las empresas dependen cada vez más de datos, conectividad, chips y plataformas digitales.",
        "La guerra tecnológica no se pelea con tanques, sino con chips, algoritmos y restricciones comerciales.",
        "¿Quién controla más el futuro: el país con más petróleo o el país con mejores chips?",
        ["Seguridad económica", "Decoupling"]
    )

def tema_6():
    mostrar_tema(
        "6. CHINA EN AMÉRICA LATINA Y MÉXICO",
        "China ha aumentado su presencia en América Latina mediante comercio, inversión, financiamiento e infraestructura.",
        "La región puede beneficiarse, pero también volverse dependiente de productos y capital chino.",
        "México puede aprovechar el nearshoring, pero también compite con China en manufactura.",
        "México está en una posición estratégica porque comercia con China, pero depende mucho de Estados Unidos.",
        "¿México debería acercarse más a China o cuidar más su relación con Estados Unidos?",
        ["Sharp power", "Seguridad económica"]
    )

def tema_7():
    mostrar_tema(
        "7. MAR DEL SUR DE CHINA",
        "Es una zona estratégica por donde pasan rutas comerciales esenciales y donde China ha construido islas artificiales con infraestructura militar.",
        "Controlar esa zona significa influir sobre una parte enorme del comercio marítimo mundial.",
        "Una crisis ahí puede afectar transporte marítimo, seguros, petróleo, comercio y cadenas de suministro.",
        "A veces una isla artificial puede tener más valor estratégico que una ciudad.",
        "¿Por qué controlar el mar puede ser tan importante como controlar tierra?",
        ["Multipolaridad", "Seguridad económica"]
    )

def tema_8():
    mostrar_tema(
        "8. CHINA Y RUSIA",
        "China y Rusia mantienen una relación estratégica basada en oposición a la influencia occidental, aunque no son aliados perfectos.",
        "Su relación puede fortalecer un bloque alternativo frente a Estados Unidos y Europa.",
        "Afecta mercados de energía, sanciones, comercio internacional y rutas financieras.",
        "China puede beneficiarse de Rusia sin depender completamente de ella.",
        "¿China y Rusia son verdaderos aliados o solo socios por conveniencia?",
        ["Multipolaridad", "Sharp power"]
    )

def tema_9():
    mostrar_tema(
        "9. RIESGOS ECONÓMICOS INTERNOS DE CHINA",
        "China enfrenta desaceleración económica, envejecimiento poblacional, crisis inmobiliaria, desempleo juvenil y deuda local.",
        "Si China se desacelera, afecta a todo el mundo porque es una pieza central del comercio global.",
        "Puede bajar la demanda de materias primas, afectar exportaciones y modificar inversiones globales.",
        "El mayor reto de China podría no ser Estados Unidos, sino sus propios problemas internos.",
        "¿Una potencia puede ser fuerte hacia afuera pero vulnerable por dentro?",
        ["Seguridad económica"]
    )

# ============================================================
# TRIVIA
# ============================================================

def modo_trivia():
    limpiar_pantalla()
    mostrar_hero("🎯 MODO TRIVIA", "Pon a prueba tu análisis geopolítico")

    puntaje = 0

    for i, pregunta in enumerate(TRIVIA_PREGUNTAS, start=1):
        limpiar_pantalla()
        mostrar_subhero(f"Pregunta {i} de {len(TRIVIA_PREGUNTAS)}", "Procesando conocimiento geopolítico...")

        mostrar_tarjeta("❓ Pregunta", pregunta["pregunta"], "card")

        respuesta = input("Tu respuesta: ").strip()
        respuesta_n = normalizar_texto(respuesta)
        validas_n = [normalizar_texto(x) for x in pregunta["validas"]]

        if respuesta_n in validas_n:
            mostrar_tarjeta("✅ Correcto", "Muy buena respuesta. Tu radar geopolítico está funcionando correctamente.", "card-green")
            puntaje += 1
        else:
            mostrar_tarjeta("❌ Incorrecto", f"Respuesta esperada: <b>{pregunta['respuesta_mostrada']}</b>", "card-red")

        mostrar_tarjeta("📘 Explicación", pregunta["explicacion"], "card")
        input("\nPulsa Enter para continuar con la siguiente pregunta...")

    limpiar_pantalla()
    mostrar_hero("🏁 RESULTADO FINAL", "Reporte estratégico generado")

    mensaje = f"Tu puntaje fue: <b>{puntaje} de {len(TRIVIA_PREGUNTAS)}</b>"

    if puntaje == 5:
        mensaje += "<br><br>🏆 Nivel excelente: visión geopolítica de alto nivel."
    elif puntaje >= 3:
        mensaje += "<br><br>🌟 Buen nivel: tienes una base sólida."
    else:
        mensaje += "<br><br>📚 Nivel inicial: sigue explorando el centro de análisis."

    display(HTML(f'<div class="score-box"><h2 style="margin-top:0;">Resultado</h2><p style="margin-bottom:0; line-height:1.7;">{mensaje}</p></div>'))

    input("\nPulsa Enter para volver al menú principal...")
    pausa_regreso()

# ============================================================
# SIMULADOR
# ============================================================

def mostrar_escenario(clave):
    escenario = ESCENARIOS[clave]
    limpiar_pantalla()
    mostrar_hero(f"🔮 {escenario['titulo']}", "Procesando escenario internacional...")

    consecuencias_html = "".join([f"<li>{c}</li>" for c in escenario["consecuencias"]])

    display(HTML(f"""
    <div class="card-red">
        <h3 style="margin-top:0;">⚠️ Consecuencias posibles</h3>
        <ul style="line-height:1.8; margin-bottom:0;">
            {consecuencias_html}
        </ul>
    </div>
    """))

    mostrar_tarjeta("💼 Lectura estratégica", escenario["impacto"], "card-gold")

    input("\nPulsa Enter para regresar al simulador...")
    pausa_regreso()

def simulador():
    while True:
        limpiar_pantalla()
        mostrar_hero("🧪 SIMULADOR “¿QUÉ PASARÍA SI...?”", "Explora escenarios internacionales de alto impacto")

        display(HTML("""
        <div class="menu-box">
            <div class="menu-item"><span class="tag">A</span><br><b>China invade Taiwán</b></div>
            <div class="menu-item"><span class="tag">B</span><br><b>EE. UU. bloquea chips avanzados a China</b></div>
            <div class="menu-item"><span class="tag">C</span><br><b>México aumenta su comercio con China</b></div>
            <div class="menu-item"><span class="tag">D</span><br><b>China controla rutas marítimas estratégicas</b></div>
        </div>
        """))

        print("\n0. Volver al menú principal")
        opcion = input("\nElige un escenario (A, B, C, D o 0): ").strip().upper()

        if opcion in ["A", "B", "C", "D"]:
            mostrar_escenario(opcion)
        elif opcion == "0":
            break
        else:
            print("⚠️ Opción no válida.")
            time.sleep(1)

# ============================================================
# SALIDA
# ============================================================

def despedida():
    limpiar_pantalla()
    mostrar_hero("👋 SALIDA DEL SISTEMA", "Cerrando centro de análisis...")

    mostrar_tarjeta(
        "✅ Sesión terminada",
        "Gracias por explorar <b>La Geopolítica de China</b>. Recuerda que entender la geopolítica ayuda a comprender negocios, tecnología, comercio, poder y riesgos globales.",
        "card-green"
    )

# ============================================================
# PROGRAMA PRINCIPAL
# ============================================================

def main():
    cargar_estilos()
    mostrar_bienvenida()

    while True:
        mostrar_menu()
        opcion = pedir_opcion_menu()

        if opcion == "1":
            tema_1()
        elif opcion == "2":
            tema_2()
        elif opcion == "3":
            tema_3()
        elif opcion == "4":
            tema_4()
        elif opcion == "5":
            tema_5()
        elif opcion == "6":
            tema_6()
        elif opcion == "7":
            tema_7()
        elif opcion == "8":
            tema_8()
        elif opcion == "9":
            tema_9()
        elif opcion == "10":
            modo_trivia()
        elif opcion == "11":
            simulador()
        elif opcion == "12":
            despedida()
            break

# Ejecutar programa
main()